# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer --self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

